# Generated by Django 4.2.8 on 2026-04-29 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quan_ly_nguoi_dung', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_dung', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='loai_nguoi_dung',
            field=models.CharField(choices=[('doc_gia', 'Độc giả'), ('thu_thu', 'Thủ thư'), ('quan_tri', 'Quản trị viên')], max_length=20),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='so_dien_thoai',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='trang_thai_tot_nghiep',
            field=models.BooleanField(default=False),
        ),
    ]
