# Generated by Django 4.2.8 on 2026-04-29 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_tai_khoan', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaiKhoan',
        ),
    ]
