# Generated by Django 4.2.8 on 2026-04-18 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quan_ly_nguoi_dung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('ma_nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tai_khoan', serialize=False, to='quan_ly_nguoi_dung.nguoidung')),
                ('mat_khau', models.CharField(max_length=255)),
                ('vai_tro', models.CharField(max_length=50)),
                ('trang_thai_tai_khoan', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tài khoản',
                'verbose_name_plural': 'Tài khoản',
                'db_table': 'TaiKhoan',
                'ordering': ['ma_nguoi_dung'],
            },
        ),
    ]
