# Generated by Django 4.2.8 on 2026-04-19 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('ma_sach', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('ten_sach', models.CharField(max_length=255)),
                ('ten_tac_gia', models.CharField(blank=True, max_length=255, null=True)),
                ('the_loai', models.CharField(blank=True, max_length=100, null=True)),
                ('ten_nha_xuat_ban', models.CharField(blank=True, max_length=255, null=True)),
                ('nam_xuat_ban', models.PositiveIntegerField()),
                ('so_luong', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Sách',
                'verbose_name_plural': 'Sách',
                'db_table': 'Sach',
            },
        ),
        migrations.CreateModel(
            name='SachTrongKho',
            fields=[
                ('ma_sach_trong_kho', models.CharField(editable=False, max_length=25, primary_key=True, serialize=False)),
                ('ma_vach', models.CharField(editable=False, max_length=50, unique=True)),
                ('trang_thai_sach', models.CharField(choices=[('available', 'Có sẵn'), ('borrowed', 'Đang mượn'), ('overdue', 'Quá hạn'), ('awaiting_replacement', 'Chờ đền sách'), ('processed', 'Đã xử lý (Đã đền bù)'), ('damaged', 'Hư hỏng'), ('lost', 'Đã mất')], default='available', max_length=30)),
                ('ma_sach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sach_trong_kho', to='quan_ly_sach.sach')),
            ],
            options={
                'verbose_name': 'Sách trong kho',
                'verbose_name_plural': 'Sách trong kho',
                'db_table': 'SachTrongKho',
                'ordering': ['ma_sach_trong_kho'],
            },
        ),
    ]
