# Generated by Django 4.2.8 on 2026-05-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_sach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sachtrongkho',
            name='trang_thai_sach',
            field=models.CharField(choices=[('available', 'Có sẵn'), ('borrowed', 'Đang mượn'), ('overdue', 'Quá hạn'), ('awaiting_replacement', 'Chờ đền sách'), ('processed', 'Đã xử lý (Đã đền bù)'), ('damaged', 'Hư hỏng'), ('lost', 'Đã mất'), ('discontinued', 'Ngừng sử dụng')], default='available', max_length=30),
        ),
    ]
