# Generated by Django 4.2.8 on 2026-04-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('ma_nguoi_dung', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('loai_nguoi_dung', models.CharField(max_length=50)),
                ('ho_ten', models.CharField(max_length=255)),
                ('lop', models.CharField(blank=True, max_length=50, null=True)),
                ('trang_thai_tot_nghiep', models.BooleanField(blank=True, null=True)),
                ('email', models.CharField(default='0', max_length=100)),
                ('so_dien_thoai', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
                'db_table': 'NguoiDung',
                'ordering': ['ho_ten'],
            },
        ),
    ]
