# Generated by Django 4.2.8 on 2026-04-19 18:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quan_ly_sach', '0001_initial'),
        ('quan_ly_nguoi_dung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhieuMuon',
            fields=[
                ('ma_phieu_muon', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ngay_muon', models.DateField(default=django.utils.timezone.now)),
                ('trang_thai', models.CharField(max_length=50)),
                ('ma_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phieu_muon', to='quan_ly_nguoi_dung.nguoidung')),
                ('nguoi_tao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phieu_muon_da_tao', to='quan_ly_nguoi_dung.nguoidung')),
            ],
            options={
                'verbose_name': 'Phiếu mượn',
                'verbose_name_plural': 'Phiếu mượn',
                'db_table': 'PhieuMuon',
                'ordering': ['-ngay_muon'],
            },
        ),
        migrations.CreateModel(
            name='ChiTietPhieuMuon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('han_tra', models.DateField()),
                ('ngay_tra', models.DateField(blank=True, null=True)),
                ('tinh_trang_khi_tra', models.CharField(blank=True, max_length=100, null=True)),
                ('ngay_khai_bao_mat', models.DateField(blank=True, null=True)),
                ('phuong_an_boi_thuong', models.CharField(blank=True, choices=[('', 'Chưa chọn'), ('den_bu_tien', 'Bồi thường tiền'), ('den_sach_moi', 'Đền sách mới')], default='', max_length=20, verbose_name='Phương án bồi thường')),
                ('ma_phieu_muon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_phieu_muon', to='muon_sach.phieumuon')),
                ('ma_sach_trong_kho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chi_tiet_phieu_muon', to='quan_ly_sach.sachtrongkho')),
            ],
            options={
                'verbose_name': 'Chi tiết phiếu mượn',
                'verbose_name_plural': 'Chi tiết phiếu mượn',
                'db_table': 'ChiTietPhieuMuon',
            },
        ),
        migrations.AddConstraint(
            model_name='chitietphieumuon',
            constraint=models.UniqueConstraint(fields=('ma_phieu_muon', 'ma_sach_trong_kho'), name='unique_chi_tiet_phieu_muon'),
        ),
    ]
