# Generated by Django 4.2.8 on 2026-04-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muon_sach', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phieumuon',
            options={'ordering': ['-ngay_muon'], 'permissions': [('extend_phieumuon', 'Can extend borrow slip')], 'verbose_name': 'Phiếu mượn', 'verbose_name_plural': 'Phiếu mượn'},
        ),
        migrations.AlterField(
            model_name='phieumuon',
            name='trang_thai',
            field=models.CharField(choices=[('dang_muon', 'Đang mượn'), ('qua_han', 'Quá hạn'), ('da_tra', 'Đã trả'), ('dang_xu_ly', 'Đang xử lý'), ('cho_den_sach', 'Chờ đền sách')], default='dang_muon', max_length=20, verbose_name='Trạng thái mượn'),
        ),
    ]
